//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "daily_tasks"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i64,
    pub name: String,
    pub start_minute: i64,
    pub end_minute: i64,
    pub duration_minutes: i64,
    pub color: String,
    pub category_id: Option<i64>,
    pub include_weekends: bool,
    pub enabled: bool,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    StartMinute,
    EndMinute,
    DurationMinutes,
    Color,
    CategoryId,
    IncludeWeekends,
    Enabled,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::StartMinute => ColumnType::BigInteger.def(),
            Self::EndMinute => ColumnType::BigInteger.def(),
            Self::DurationMinutes => ColumnType::BigInteger.def(),
            Self::Color => ColumnType::String(StringLen::None).def(),
            Self::CategoryId => ColumnType::BigInteger.def().null(),
            Self::IncludeWeekends => ColumnType::Boolean.def(),
            Self::Enabled => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::String(StringLen::None).def(),
            Self::UpdatedAt => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
