//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::daily_tasks::Entity as DailyTasks;
pub use super::daily_plans::Entity as DailyPlans;
pub use super::categories::Entity as Categories;
